import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";

export const metadata: Metadata = {
 title: "Totalne koty | Narzędzia",
 description: "Generated by create next app",
};

const fontSans = FontSans({
 subsets: ["latin"],
 variable: "--font-sans",
});

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <Providers>
    <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>{children}</body>
   </Providers>
  </html>
 );
}
